"""Build the installable version of the game into docs/ (that is the folder GitHub Pages serves).

Differences from the local build:
  * the ~800 separate voice clips become three mp3 sprites (tools/build_sprite.py);
  * the page gets a web app manifest, icons and a service worker, so it installs on a phone
    home screen and keeps working with no signal;
  * the service worker version is a hash of the files, so a push updates the app by itself.

python tools/build_artifact.py
"""
import os, re, json, shutil, hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, 'docs')
APP_NAME = 'SVIATOSAURUS'
THEME = '#ff8a1f'
BG = '#ff9f43'
os.makedirs(DIST, exist_ok=True)

# ---------- page ----------
html = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
head = html.split('<head>', 1)[1].split('</head>', 1)[0]
body = html.split('<body>', 1)[1].split('</body>', 1)[0]

keep = []
for m in re.finditer(r'<title>.*?</title>|<link [^>]*>', head, re.S):
    t = m.group(0)
    if 'viewport' in t or 'charset' in t: continue
    keep.append(t.strip())

META = ('<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">\n'
        f'<meta name="theme-color" content="{THEME}">\n'
        '<meta name="mobile-web-app-capable" content="yes">\n'
        '<meta name="apple-mobile-web-app-capable" content="yes">\n'
        '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n'
        f'<meta name="apple-mobile-web-app-title" content="{APP_NAME}">\n'
        '<link rel="manifest" href="manifest.webmanifest">\n'
        '<link rel="apple-touch-icon" href="assets/icons/apple-180.png">\n')
SW_REG = ('\n<script>\n'
          "if ('serviceWorker' in navigator) addEventListener('load', () => navigator.serviceWorker.register('sw.js').catch(() => {}));\n"
          '</script>\n')

body = body.replace('audio/voice-manifest.js', 'audio/voice-sprite.js')
page = META + '\n'.join(keep) + '\n' + body.strip() + SW_REG
open(os.path.join(DIST, 'index.html'), 'w', encoding='utf-8').write(page)

# ---------- what ships ----------
files = {}
for m in re.finditer(r'(?:src|href)="([^"]+)"', page):
    u = m.group(1)
    if u.startswith('http') or u.startswith('data:') or u == 'manifest.webmanifest' or u == 'sw.js': continue
    files[u] = u
for f in sorted(os.listdir(os.path.join(ROOT, 'assets', 'img'))):
    if f.endswith('.png'): files['assets/img/' + f] = 'assets/img/' + f
for f in sorted(os.listdir(os.path.join(ROOT, 'assets', 'icons'))):
    if f.endswith('.png'): files['assets/icons/' + f] = 'assets/icons/' + f
audio = []
for f in sorted(os.listdir(os.path.join(DIST, 'audio'))) if os.path.isdir(os.path.join(DIST, 'audio')) else []:
    if f.endswith('.mp3'): audio.append('audio/' + f); files['audio/' + f] = 'docs/audio/' + f

total, digest = 0, hashlib.sha1()
for pub, src in sorted(files.items()):
    p = os.path.join(ROOT, src)
    if not os.path.exists(p): print('MISSING', src); continue
    total += os.path.getsize(p)
    dest = os.path.join(DIST, pub.replace('/', os.sep))
    if os.path.abspath(dest) != os.path.abspath(p):
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        if not (os.path.exists(dest) and os.path.getmtime(dest) >= os.path.getmtime(p)): shutil.copy2(p, dest)
    with open(p, 'rb') as fh: digest.update(pub.encode()); digest.update(fh.read())
digest.update(page.encode())
version = digest.hexdigest()[:10]

# ---------- manifest ----------
manifest = {
    'name': APP_NAME, 'short_name': APP_NAME.title(), 'description': 'A dinosaur world for Sviatko',
    'start_url': './', 'scope': './', 'display': 'fullscreen', 'display_override': ['fullscreen', 'standalone'],
    'orientation': 'any', 'background_color': BG, 'theme_color': THEME, 'lang': 'en',
    'icons': [
        {'src': 'assets/icons/icon-192.png', 'sizes': '192x192', 'type': 'image/png'},
        {'src': 'assets/icons/icon-512.png', 'sizes': '512x512', 'type': 'image/png'},
        {'src': 'assets/icons/maskable-512.png', 'sizes': '512x512', 'type': 'image/png', 'purpose': 'maskable'}
    ]
}
open(os.path.join(DIST, 'manifest.webmanifest'), 'w', encoding='utf-8').write(json.dumps(manifest, indent=1))

# ---------- service worker ----------
shell = ['./', 'index.html', 'manifest.webmanifest'] + [f for f in sorted(files) if f not in audio]
sw = f"""/* {APP_NAME} — offline shell. Generated by tools/build_artifact.py; do not edit by hand. */
const V = 'sv-{version}';
const SHELL = {json.dumps(shell, indent=1)};
const VOICE = {json.dumps(audio, indent=1)};

self.addEventListener('install', (e) => {{
  e.waitUntil((async () => {{
    const c = await caches.open(V);
    await c.addAll(SHELL.map(u => new Request(u, {{ cache: 'reload' }})));
    self.skipWaiting();
  }})());
}});

self.addEventListener('activate', (e) => {{
  e.waitUntil((async () => {{
    for (const k of await caches.keys()) if (k !== V) await caches.delete(k);
    await self.clients.claim();
    /* pull the voice down quietly, so the game also talks with no signal */
    const c = await caches.open(V);
    for (const u of VOICE) {{ try {{ if (!(await c.match(u))) await c.add(new Request(u, {{ cache: 'reload' }})); }} catch (err) {{ }} }}
  }})());
}});

self.addEventListener('fetch', (e) => {{
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  e.respondWith((async () => {{
    const c = await caches.open(V);
    const hit = await c.match(req, {{ ignoreSearch: true }});
    if (hit) return hit;
    try {{
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') c.put(req, res.clone());
      return res;
    }} catch (err) {{
      return hit || new Response('', {{ status: 504 }});
    }}
  }})());
}});
"""
open(os.path.join(DIST, 'sw.js'), 'w', encoding='utf-8').write(sw)

print('%d files, %.1f MB, version %s' % (len(files), total / 1e6, version))
print('site:', DIST)
