"""Glue every voice clip into a few big MP3 sprites, so the game can be published as a web page
(a page may only carry a couple of hundred files, and we have ~800 clips).

The clips are CBR 128 kbps / 44.1 kHz with no ID3 tag, so frames can simply be concatenated and the
position of each clip is exactly (frames before it) x 1152 / 44100 seconds. A short silent gap is
written between clips so that a seek that lands a frame early still lands in silence.

python tools/build_sprite.py            ->  dist/audio/voice-N.mp3 + audio/voice-sprite.js
"""
import os, json, hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'audio', 'voice')
OUT = os.path.join(ROOT, 'docs', 'audio')
MAX_BYTES = 11 * 1024 * 1024          # keep every sprite well under the 15 MB per-file limit
FRAME_SEC = 1152 / 44100.0
GAP_FRAMES = 6                        # ~157 ms of silence between clips

BITRATES = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0]
RATES = [44100, 48000, 32000, 0]


def frames(data):
    """[(offset, length)] of every MPEG audio frame, plus the header bytes"""
    out = []; i = 0; hdr = None
    if data[:3] == b'ID3':
        i = 10 + ((data[6] & 0x7f) << 21 | (data[7] & 0x7f) << 14 | (data[8] & 0x7f) << 7 | (data[9] & 0x7f))
    while i + 4 <= len(data):
        if data[i] == 0xFF and (data[i + 1] & 0xE0) == 0xE0:
            br = BITRATES[(data[i + 2] >> 4) & 0xF]; sr = RATES[(data[i + 2] >> 2) & 3]
            if br == 0 or sr == 0: i += 1; continue
            pad = (data[i + 2] >> 1) & 1
            ln = 144 * br * 1000 // sr + pad
            if hdr is None: hdr = data[i:i + 4]
            out.append((i, ln)); i += ln
        else: i += 1
    return out, hdr


def silence(hdr):
    """one frame of digital silence with the same header as the clips"""
    br = BITRATES[(hdr[2] >> 4) & 0xF]; sr = RATES[(hdr[2] >> 2) & 3]
    ln = 144 * br * 1000 // sr + ((hdr[2] >> 1) & 1)
    return bytes(hdr) + b'\x00' * (ln - 4)


def main():
    os.makedirs(OUT, exist_ok=True)
    raw = open(os.path.join(ROOT, 'audio', 'voice-manifest.js'), encoding='utf-8').read()
    manifest = json.loads(raw.split('DW.VOICE_MANIFEST = ', 1)[1].rsplit(';', 1)[0])

    sprites, cur, cur_frames, index, n = [], bytearray(), 0, {}, 0
    gap = None
    for text, name in manifest.items():
        p = os.path.join(SRC, name + '.mp3')
        if not os.path.exists(p): continue
        data = open(p, 'rb').read()
        fr, hdr = frames(data)
        if not fr: continue
        if gap is None: gap = silence(hdr) * GAP_FRAMES
        body = data[fr[0][0]:fr[-1][0] + fr[-1][1]]
        if len(cur) + len(body) + len(gap) > MAX_BYTES:
            sprites.append(bytes(cur)); cur = bytearray(); cur_frames = 0; n += 1
        cur += gap; cur_frames += GAP_FRAMES
        start = cur_frames * FRAME_SEC
        cur += body; cur_frames += len(fr)
        index[text] = [n, round(start, 3), round(len(fr) * FRAME_SEC, 3)]
    sprites.append(bytes(cur))

    for i, s in enumerate(sprites):
        open(os.path.join(OUT, 'voice-%d.mp3' % i), 'wb').write(s)
        print('voice-%d.mp3  %.1f MB' % (i, len(s) / 1e6))
    with open(os.path.join(ROOT, 'audio', 'voice-sprite.js'), 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/build_sprite.py — text -> [sprite, start, duration] */\n'
                'window.DW = window.DW || {};\nDW.VOICE_SPRITE = { files: %s, clips: %s };\n'
                % (json.dumps(['audio/voice-%d.mp3' % i for i in range(len(sprites))]), json.dumps(index, ensure_ascii=False)))
    print('clips', len(index), 'sprites', len(sprites))


if __name__ == '__main__':
    main()
